meta_product_name: "TakeCare"
meta_title: "TakeCare - Ready when you are not"
meta_description: "Saying goodbye to loved ones - especially when it comes suddenly and unexpectedly - is particularly painful for family members and friends. We made it our task to build a platform that organizes the wishes regarding the after life of your loved ones before hand. "
meta_image: "cover.png"
twitter_account: "@take_care"
